import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Ensure the generated-files directory exists
const generatedFilesDir = path.join(__dirname, '..', 'generated-files');

if (!fs.existsSync(generatedFilesDir)) {
  fs.mkdirSync(generatedFilesDir, { recursive: true });
}

export function generateSummaryFile(meeting, summary, retrospectives) {
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const fileName = `meeting-summary-${meeting.meetingId}-${timestamp}.txt`;
    const filePath = path.join(generatedFilesDir, fileName);
    
    // Get participant count
    const participantCount = retrospectives.length;
    
    // Format the content
    const content = formatSummaryContent(meeting, summary, retrospectives, participantCount);
    
    // Write the file
    fs.writeFileSync(filePath, content, 'utf8');
    
    console.log(`Summary file generated: ${fileName}`);
    return { fileName, filePath };
  } catch (error) {
    console.error('Error generating summary file:', error);
    throw new Error('Failed to generate summary file: ' + error.message);
  }
}

function formatSummaryContent(meeting, summary, retrospectives, participantCount) {
  const generatedAt = new Date().toLocaleString();
  const meetingTime = meeting.organizerTime ? new Date(meeting.organizerTime).toLocaleString() : 'Not specified';
  
  return `
MEETING SUMMARY REPORT
=====================

Meeting Information:
-------------------
Meeting ID: ${meeting.meetingId}
Meeting Title: ${meeting.title}
Meeting Time: ${meetingTime}
Platform: ${meeting.platform || 'Not specified'}
Host Email: ${meeting.hostEmail || 'Not specified'}
Total Participants: ${participantCount}
Summary Generated: ${generatedAt}
Trigger Reason: ${summary.triggerReason}

EXECUTIVE SUMMARY:
-----------------
${summary.summaryText}

DETAILED RETROSPECTIVE FEEDBACK:
--------------------------------
${retrospectives.map((r, index) => {
  const participant = r.participant || {};
  const scores = r.scores ? formatScores(r.scores) : 'No scores provided';
  
  return `
Participant ${index + 1}:
- Email: ${participant.email || r.email}
- Name: ${participant.name || 'Not provided'}
- Role: ${participant.role || 'participant'}
- Submitted: ${r.createdAt ? new Date(r.createdAt).toLocaleString() : 'Unknown'}
- Feedback: ${r.content}
- Scores: ${scores}
${'='.repeat(50)}`;
}).join('\n')}

RECOMMENDATIONS:
---------------
Based on the retrospective feedback, consider the following:

1. Review the key themes and patterns identified in the summary
2. Address any action items mentioned by participants
3. Focus on areas for improvement in future meetings
4. Continue practices that received positive feedback
5. Follow up with participants on any specific concerns raised

---
Generated by Convene Meeting System
For questions or support, contact your system administrator
`;
}

function formatScores(scores) {
  if (typeof scores === 'object' && scores !== null) {
    return Object.entries(scores)
      .map(([key, value]) => `${key}: ${value}`)
      .join(', ');
  }
  return String(scores);
}

export function cleanupOldFiles() {
  try {
    const files = fs.readdirSync(generatedFilesDir);
    const now = Date.now();
    const maxAge = 24 * 60 * 60 * 1000; // 24 hours in milliseconds
    
    files.forEach(file => {
      const filePath = path.join(generatedFilesDir, file);
      const stats = fs.statSync(filePath);
      
      if (now - stats.mtime.getTime() > maxAge) {
        fs.unlinkSync(filePath);
        console.log(`Cleaned up old file: ${file}`);
      }
    });
  } catch (error) {
    console.error('Error cleaning up old files:', error);
  }
}

export function deleteFile(filePath) {
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      console.log(`File deleted: ${filePath}`);
      return true;
    }
    return false;
  } catch (error) {
    console.error('Error deleting file:', error);
    return false;
  }
}
