import nodemailer from "nodemailer";

let transporter;

export function getTransporter() {
  if (transporter) return transporter;
  const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS } = process.env;
  if (!SMTP_HOST || !SMTP_PORT || !SMTP_USER || !SMTP_PASS) {
    console.warn("SMTP not configured; emails disabled");
    return null;
  }
  transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: Number(SMTP_PORT),
    secure: Number(SMTP_PORT) === 465,
    auth: { user: SMTP_USER, pass: SMTP_PASS }
  });
  return transporter;
}

export async function sendEmail({ to, subject, html, attachments }) {
  const tx = getTransporter();
  if (!tx) return { skipped: true };
  const from = process.env.SMTP_FROM || process.env.SMTP_USER;
  return tx.sendMail({ from, to, subject, html, attachments });
}

export function renderMeetingEmail(meeting) {
  const lines = [];
  lines.push(`<h2>${meeting.title}</h2>`);
  lines.push(`<p><strong>Meeting ID:</strong> ${meeting.meetingId}</p>`);
  if (meeting.organizerTime) lines.push(`<p><strong>Organizer Time:</strong> ${meeting.organizerTime}</p>`);
  if (meeting.clientTime) lines.push(`<p><strong>Client Time:</strong> ${meeting.clientTime}</p>`);
  lines.push(`<p><strong>Platform:</strong> ${meeting.platform || "Google Meet"}</p>`);
  return lines.join("");
}

export async function sendSummaryEmail(meeting, summary, filePath) {
  const tx = getTransporter();
  if (!tx) return { skipped: true };
  
  const from = process.env.SMTP_FROM || process.env.SMTP_USER;
  const subject = `Meeting Summary Report: ${meeting.title}`;
  
  // Create HTML content for the email
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px;">
        📊 Meeting Summary Report
      </h2>
      
      <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <h3 style="margin-top: 0; color: #495057;">Meeting Details</h3>
        <p><strong>Meeting ID:</strong> ${meeting.meetingId}</p>
        <p><strong>Title:</strong> ${meeting.title}</p>
        <p><strong>Platform:</strong> ${meeting.platform || 'Not specified'}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        <p><strong>Trigger:</strong> ${summary.triggerReason.replace('_', ' ').toUpperCase()}</p>
      </div>
      
      <div style="background: #e3f2fd; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <h3 style="margin-top: 0; color: #1976d2;">Summary Preview</h3>
        <div style="background: white; padding: 10px; border-radius: 3px; max-height: 200px; overflow-y: auto;">
          ${summary.summaryText.substring(0, 500)}${summary.summaryText.length > 500 ? '...' : ''}
        </div>
      </div>
      
      <div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <h3 style="margin-top: 0; color: #856404;">📎 Attachment</h3>
        <p>Please find the complete summary report attached as a text file. The attachment contains:</p>
        <ul>
          <li>Detailed retrospective feedback from all participants</li>
          <li>Individual scores and ratings</li>
          <li>Action items and recommendations</li>
          <li>Complete meeting analysis</li>
        </ul>
      </div>
      
      <div style="text-align: center; margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 5px;">
        <p style="margin: 0; color: #6c757d; font-size: 14px;">
          Generated by <strong>Convene Meeting System</strong><br>
          For questions or support, contact your system administrator
        </p>
      </div>
    </div>
  `;
  
  // Prepare attachments
  const attachments = [];
  if (filePath) {
    attachments.push({
      filename: `meeting-summary-${meeting.meetingId}.txt`,
      path: filePath
    });
  }
  
  try {
    const result = await tx.sendMail({
      from,
      to: meeting.hostEmail,
      subject,
      html,
      attachments
    });
    
    console.log(`Summary email sent to ${meeting.hostEmail}`);
    return result;
  } catch (error) {
    console.error('Error sending summary email:', error);
    throw error;
  }
}


